### ISSUE TITLE
[Feature Request] Please update `intl` dependency to latest version (>=0.20.2)

### ISSUE THREAD

**Issue by Yang-Jiankun** [nank1ro/flutter-shadcn-ui#308]
### Description
Currently, `flutter-shadcn-ui` depends on `intl ^0.19.0`, but the latest `intl` version is `0.20.2`. This causes conflicts in projects that require newer versions of `intl`.

### Proposed Solution
Please update the `intl` dependency in `pubspec.yaml` to:
```yaml
intl: ^0.20.2


### Expected results

### Proposed Solution
Please update the `intl` dependency in `pubspec.yaml` to:
```yaml
intl: ^0.20.2

### Actual results

Currently, `flutter-shadcn-ui` depends on `intl ^0.19.0`

### shadcn_ui version

0.21.0

### Platform

MacOS, iOS

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>
