### ISSUE TITLE
Theming question

### ISSUE THREAD

**Issue by eb-so** [nank1ro/flutter-shadcn-ui#36]
How to import `ShadcnTheme` 
<img width="753" alt="Screenshot 2024-02-29 at 12 39 53 AM" src="https://github.com/nank1ro/flutter-shadcn-ui/assets/89080323/5d499973-6492-48a7-b47e-d6cfd8b8fd00">

**Comment by nank1ro** [comment]
Everything on this library is exported in the `shadcn_ui` barrel file.
You just need to import it:
```dart
import 'package:shadcn_ui/shadcn_ui.dart';
```

**Comment by eb-so** [comment]
I searched in your repo for `ShadcnTheme` but didn't find anything, and the import above didn't help 😞

**Comment by eb-so** [comment]
BTW This is how I'm using the package
```
  shadcn_ui:
    git:
      url: https://github.com/nank1ro/flutter-shadcn-ui.git
      ref: main
  ```

**Comment by nank1ro** [comment]
Can you share your code?
Are your working on a fork of the library or importing it in a project?

**Comment by eb-so** [comment]
@nank1ro Oh found the issue
it's `ShadTheme` not `ShadcnTheme`

**Comment by nank1ro** [comment]
> BTW This is how I'm using the package
> 
> ```
> 
>   shadcn_ui:
> 
>     git:
> 
>       url: https://github.com/nank1ro/flutter-shadcn-ui.git
> 
>       ref: main
> 
>   ```

Strage.. can you try this one instead?
```yaml

shadcn_ui:
    git:
      url: git@github.com:nank1ro/flutter-shadcn-ui.git
      ref: main
```
