### ISSUE TITLE
Google Font not being set

### ISSUE THREAD

**Issue by Pietervdw** [nank1ro/flutter-shadcn-ui#87]
### Steps to reproduce

Following the instructions in the documentation to set the font to a Google font: https://mariuti.com/shadcn-ui/typography/#google-font

Not sure what I'm missing, apologies if it's something I've missed.

### Expected results

The font should update to the specified Google Font

### Actual results

Font stays on the default.

### Platform

Android

### Code sample

```dart
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ShadApp(
      themeMode: ThemeMode.light,
      theme: ShadThemeData(
        brightness: Brightness.light,
        textTheme: ShadTextTheme.fromGoogleFont(GoogleFonts.aguafinaScript),
        colorScheme: const ShadSlateColorScheme.light(),
      ),
      darkTheme: ShadThemeData(
        brightness: Brightness.dark,
        textTheme: ShadTextTheme.fromGoogleFont(GoogleFonts.aguafinaScript),
        colorScheme: const ShadSlateColorScheme.dark(),
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Shadcdn-ui"),
      ),
      body: const Center(
        child: Text("Hello World"),
      ),
    );
  }
}
```

Pubspec:

```yaml

name: untitled1
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shadcn_ui: ^0.6.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
```  

### Flutter Doctor output

```console
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3737], locale en-ZA)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.10.0)
[√] Android Studio (version 2023.2)
[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
[√] VS Code (version 1.90.2)
[√] Connected device (4 available)
[√] Network resources

```
